import typing
from PyQt5 import QtCore
from PyQt5.QtGui import QFont, QIcon, QPalette, QBrush, QColor
from PyQt5.QtCore import Qt, QSize, QMetaObject, QCoreApplication
from PyQt5.QtWidgets import (
    QWidget, QVBoxLayout, QDoubleSpinBox, 
    QHBoxLayout, QPushButton, QFrame, QLabel
)


class Ui_Calibration(object):
    def setupUi(self, Window):
        Window.setObjectName("SpectrumDemo")
        Window.resize(900, 600)
        Window.setMinimumSize(QSize(900, 600))
        Window.setMaximumSize(QSize(16777215, 16777215))
        font = QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        Window.setFont(font)
        Window.setStyleSheet("QPushButton{\nbackground-color: rgb(85, 85, 127);\ncolor: rgb(255, 255, 255);\n}\nQPushButton:pressed{\nbackground-color: rgb(55, 55,  97);\n}")
        self.centralwidget = QWidget(Window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.service_layout = QFrame(self.centralwidget)
        self.service_layout.setMinimumSize(QSize(0, 50))
        self.service_layout.setMaximumSize(QSize(16777215, 100))
        self.service_layout.setFrameShape(QFrame.StyledPanel)
        self.service_layout.setFrameShadow(QFrame.Raised)
        self.service_layout.setObjectName("service_layout")
        self.horizontalLayout = QHBoxLayout(self.service_layout)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.info_label = QLabel(self.service_layout)
        self.info_label.setMinimumSize(QSize(135, 0))
        self.info_label.setMaximumSize(QSize(240, 16777215))
        font = QFont()
        font.setPointSize(11)
        self.info_label.setFont(font)
        self.info_label.setAlignment(Qt.AlignCenter)
        self.info_label.setWordWrap(True)
        self.info_label.setObjectName("info_label")
        self.horizontalLayout.addWidget(self.info_label)
        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.first_layout = QHBoxLayout()
        self.first_layout.setObjectName("first_layout")
        self.first_point = QLabel(self.service_layout)
        self.first_point.setMinimumSize(QSize(150, 0))
        self.first_point.setMaximumSize(QSize(150, 16777215))
        font = QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.first_point.setFont(font)
        self.first_point.setObjectName("first_point")
        self.first_layout.addWidget(self.first_point)
        self.first_state = QDoubleSpinBox(self.service_layout)
        self.first_state.setMinimumSize(QSize(50, 0))
        self.first_state.setMaximumSize(QSize(100, 100))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush = QBrush(QColor(85, 85, 127))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush = QBrush(QColor(85, 85, 127))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        brush = QBrush(QColor(85, 85, 127))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        brush = QBrush(QColor(85, 85, 127))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        brush = QBrush(QColor(85, 85, 127))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        brush = QBrush(QColor(85, 85, 127))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        brush = QBrush(QColor(85, 85, 127))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        brush = QBrush(QColor(85, 85, 127))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush)
        brush = QBrush(QColor(85, 85, 127))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush)
        self.first_state.setPalette(palette)
        font = QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.first_state.setFont(font)
        self.first_state.setStyleSheet("background-color: rgb(85, 85, 127);\ncolor: rgb(255, 255, 255);")
        self.first_state.setDecimals(3)
        self.first_state.setMaximum(9999999.0)
        self.first_state.setSingleStep(0.01)
        self.first_state.setObjectName("first_state")
        self.first_layout.addWidget(self.first_state)
        self.verticalLayout_2.addLayout(self.first_layout)
        self.second_layout = QHBoxLayout()
        self.second_layout.setObjectName("second_layout")
        self.second_point = QLabel(self.service_layout)
        self.second_point.setMinimumSize(QSize(150, 0))
        self.second_point.setMaximumSize(QSize(150, 16777215))
        font = QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.second_point.setFont(font)
        self.second_point.setObjectName("second_point")
        self.second_layout.addWidget(self.second_point)
        self.second_state = QDoubleSpinBox(self.service_layout)
        self.second_state.setMinimumSize(QSize(50, 20))
        self.second_state.setMaximumSize(QSize(100, 100))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush = QBrush(QColor(85, 85, 127))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush = QBrush(QColor(85, 85, 127))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        brush = QBrush(QColor(85, 85, 127))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        brush = QBrush(QColor(85, 85, 127))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        brush = QBrush(QColor(85, 85, 127))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        brush = QBrush(QColor(85, 85, 127))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        brush = QBrush(QColor(85, 85, 127))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        brush = QBrush(QColor(85, 85, 127))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush)
        brush = QBrush(QColor(85, 85, 127))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush)
        self.second_state.setPalette(palette)
        font = QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.second_state.setFont(font)
        self.second_state.setStyleSheet("background-color: rgb(85, 85, 127);\ncolor: rgb(255, 255, 255);")
        self.second_state.setDecimals(3)
        self.second_state.setMaximum(9999999.0)
        self.second_state.setSingleStep(0.01)
        self.second_state.setObjectName("second_state")
        self.second_layout.addWidget(self.second_state)
        self.verticalLayout_2.addLayout(self.second_layout)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.calibrate_button = QPushButton(self.service_layout)
        self.calibrate_button.setMinimumSize(QSize(110, 80))
        self.calibrate_button.setMaximumSize(QSize(500, 80))
        font = QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.calibrate_button.setFont(font)
        self.calibrate_button.setObjectName("calibrate_button")
        self.horizontalLayout.addWidget(self.calibrate_button)
        self.output = QWidget(self.service_layout)
        self.output.setMinimumSize(QSize(100, 0))
        self.output.setMaximumSize(QSize(200, 16777215))
        self.output.setStyleSheet("background-color: rgb(85, 85, 127);\ncolor: rgb(255, 255, 255);")
        self.output.setObjectName("output")
        self.horizontalLayout_2 = QHBoxLayout(self.output)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.output_label = QLabel(self.output)
        font = QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.output_label.setFont(font)
        self.output_label.setAlignment(Qt.AlignCenter)
        self.output_label.setObjectName("output_label")
        self.horizontalLayout_2.addWidget(self.output_label)
        self.horizontalLayout.addWidget(self.output)
        self.verticalLayout.addWidget(self.service_layout)
        self.matplotlib_layout = QFrame(self.centralwidget)
        self.matplotlib_layout.setFrameShape(QFrame.StyledPanel)
        self.matplotlib_layout.setFrameShadow(QFrame.Raised)
        self.matplotlib_layout.setObjectName("matplotlib_layout")
        self.verticalLayout.addWidget(self.matplotlib_layout)
        Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Window)
        QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, SpectrumDemo):
        _translate = QCoreApplication.translate
        SpectrumDemo.setWindowTitle(_translate("SpectrumDemo", "dSigma — Calibration Window"))
        self.info_label.setText(_translate("SpectrumDemo", "Pick the points on spectrum and select states of residual nuclei, then press enter or \"Calibrate\" button"))
        self.first_point.setText(_translate("SpectrumDemo", "There will shown points"))
        self.second_point.setText(_translate("SpectrumDemo", "There will shown points"))
        self.calibrate_button.setText(_translate("SpectrumDemo", "Calibrate"))
        self.output_label.setText(_translate("SpectrumDemo", "TextLabel"))


class CalibrationWindow(QWidget, Ui_Calibration):
    def __init__(self) -> None:
        super().__init__()


if __name__ == '__main__':
    pass
