from business.matrix import Matrix
from business.encoding import Encoder
from business.decoding import Decoder

from PyQt5.QtGui import QFont, QIcon, QPalette, QBrush, QColor
from PyQt5.QtCore import Qt, QSize, QMetaObject, QCoreApplication
from PyQt5.QtWidgets import (
    QWidget, QMainWindow, QVBoxLayout, 
    QComboBox, QHBoxLayout, QLineEdit, 
    QFrame, QLabel, QSpacerItem, QSizePolicy,
    QDoubleSpinBox, QPushButton
)

class Ui_FileConfigWindow(object):
    def setupUi(self, FileConfigWindow):
        FileConfigWindow.setObjectName("FileConfigWindow")
        FileConfigWindow.resize(800, 800)
        FileConfigWindow.setMinimumSize(QSize(800, 800))
        font = QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        FileConfigWindow.setFont(font)
        FileConfigWindow.setStyleSheet("QPushButton{background-color: rgb(85, 85, 127);\ncolor: rgb(255, 255, 255);font: 63 12pt \"Bahnschrift SemiBold\";}QPushButton:pressed{background-color: rgb(55, 55, 97);}")
        self.centralwidget = QWidget(FileConfigWindow)
        self.centralwidget.setLayoutDirection(Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QSpacerItem(0, 0, QSizePolicy.Preferred, QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.main_layout = QFrame(self.centralwidget)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_layout.sizePolicy().hasHeightForWidth())
        self.main_layout.setSizePolicy(sizePolicy)
        self.main_layout.setMinimumSize(QSize(600, 750))
        self.main_layout.setMaximumSize(QSize(1500, 16777215))
        self.main_layout.setStyleSheet("font: 63 14pt \"Bahnschrift SemiBold\";")
        self.main_layout.setFrameShape(QFrame.StyledPanel)
        self.main_layout.setFrameShadow(QFrame.Raised)
        self.main_layout.setObjectName("main_layout")
        self.verticalLayout = QVBoxLayout(self.main_layout)
        self.verticalLayout.setObjectName("verticalLayout")
        self.beam_layout = QHBoxLayout()
        self.beam_layout.setObjectName("beam_layout")
        self.beam_label = QLabel(self.main_layout)
        self.beam_label.setMinimumSize(QSize(370, 30))
        self.beam_label.setMaximumSize(QSize(370, 80))
        self.beam_label.setObjectName("beam_label")
        self.beam_layout.addWidget(self.beam_label)
        self.beam_line = QLineEdit(self.main_layout)
        self.beam_line.setMinimumSize(QSize(50, 40))
        self.beam_line.setMaximumSize(QSize(16777215, 80))
        self.beam_line.setStyleSheet("background-color: rgb(85, 85, 127);color: rgb(255, 255, 255);")
        self.beam_line.setAlignment(Qt.AlignCenter)
        self.beam_line.setObjectName("beam_line")
        self.beam_layout.addWidget(self.beam_line)
        self.beam_correct_label = QLabel(self.main_layout)
        self.beam_correct_label.setMaximumSize(QSize(120, 80))
        self.beam_correct_label.setObjectName("beam_correct_label")
        self.beam_layout.addWidget(self.beam_correct_label)
        self.verticalLayout.addLayout(self.beam_layout)
        self.target_layout = QHBoxLayout()
        self.target_layout.setObjectName("target_layout")
        self.target_label = QLabel(self.main_layout)
        self.target_label.setMinimumSize(QSize(370, 0))
        self.target_label.setMaximumSize(QSize(370, 80))
        self.target_label.setObjectName("target_label")
        self.target_layout.addWidget(self.target_label)
        self.target_line = QLineEdit(self.main_layout)
        self.target_line.setMinimumSize(QSize(50, 40))
        self.target_line.setMaximumSize(QSize(16777215, 80))
        self.target_line.setStyleSheet("background-color: rgb(85, 85, 127);color: rgb(255, 255, 255);")
        self.target_line.setAlignment(Qt.AlignCenter)
        self.target_line.setObjectName("target_line")
        self.target_layout.addWidget(self.target_line)
        self.target_correct_label = QLabel(self.main_layout)
        self.target_correct_label.setMaximumSize(QSize(120, 80))
        self.target_correct_label.setObjectName("target_correct_label")
        self.target_layout.addWidget(self.target_correct_label)
        self.verticalLayout.addLayout(self.target_layout)
        self.energy_layout = QHBoxLayout()
        self.energy_layout.setObjectName("energy_layout")
        self.energy_label = QLabel(self.main_layout)
        self.energy_label.setMinimumSize(QSize(370, 0))
        self.energy_label.setMaximumSize(QSize(370, 80))
        self.energy_label.setObjectName("energy_label")
        self.energy_layout.addWidget(self.energy_label)
        self.energy_box = QDoubleSpinBox(self.main_layout)
        self.energy_box.setMinimumSize(QSize(170, 40))
        self.energy_box.setMaximumSize(QSize(16777215, 80))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush = QBrush(QColor(85, 85, 127))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush = QBrush(QColor(85, 85, 127))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        brush = QBrush(QColor(85, 85, 127))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush)
        brush = QBrush(QColor(85, 85, 127))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Highlight, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        brush = QBrush(QColor(85, 85, 127))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        brush = QBrush(QColor(85, 85, 127))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        brush = QBrush(QColor(85, 85, 127))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush)
        brush = QBrush(QColor(85, 85, 127))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Highlight, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        brush = QBrush(QColor(85, 85, 127))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        brush = QBrush(QColor(85, 85, 127))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush)
        brush = QBrush(QColor(85, 85, 127))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush)
        brush = QBrush(QColor(0, 120, 215))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Highlight, brush)
        self.energy_box.setPalette(palette)
        self.energy_box.setStyleSheet("background-color: rgb(85, 85, 127);color: rgb(255, 255, 255);")
        self.energy_box.setAlignment(Qt.AlignCenter)
        self.energy_box.setDecimals(3)
        self.energy_box.setMaximum(999999.0)
        self.energy_box.setSingleStep(0.1)
        self.energy_box.setObjectName("energy_box")
        self.energy_layout.addWidget(self.energy_box)
        self.verticalLayout.addLayout(self.energy_layout)
        self.angle_layout = QHBoxLayout()
        self.angle_layout.setObjectName("angle_layout")
        self.angle_label = QLabel(self.main_layout)
        self.angle_label.setMinimumSize(QSize(370, 0))
        self.angle_label.setMaximumSize(QSize(370, 80))
        self.angle_label.setObjectName("angle_label")
        self.angle_layout.addWidget(self.angle_label)
        self.angle_box = QDoubleSpinBox(self.main_layout)
        self.angle_box.setMinimumSize(QSize(180, 40))
        self.angle_box.setMaximumSize(QSize(16777215, 80))
        self.angle_box.setPalette(palette)
        self.angle_box.setStyleSheet("background-color: rgb(85, 85, 127);color: rgb(255, 255, 255);")
        self.angle_box.setAlignment(Qt.AlignCenter)
        self.angle_box.setMaximum(999999.0)
        self.angle_box.setSingleStep(0.1)
        self.angle_box.setObjectName("angle_box")
        self.angle_layout.addWidget(self.angle_box)
        self.angle_correct_label = QLabel(self.main_layout)
        self.angle_correct_label.setMaximumSize(QSize(120, 80))
        self.angle_correct_label.setObjectName("angle_correct_label")
        self.angle_layout.addWidget(self.angle_correct_label)
        self.verticalLayout.addLayout(self.angle_layout)
        self.telescope_layout = QVBoxLayout()
        self.telescope_layout.setObjectName("telescope_layout")
        self.telescope_info = QLabel(self.main_layout)
        self.telescope_info.setMinimumSize(QSize(0, 30))
        self.telescope_info.setMaximumSize(QSize(16777215, 60))
        font = QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.telescope_info.setFont(font)
        self.telescope_info.setAlignment(Qt.AlignCenter)
        self.telescope_info.setObjectName("telescope_info")
        self.telescope_layout.addWidget(self.telescope_info)
        self.detector_layout = QHBoxLayout()
        self.detector_layout.setObjectName("detector_layout")
        self.de_layout = QVBoxLayout()
        self.de_layout.setObjectName("de_layout")
        self.de_detector_info = QLabel(self.main_layout)
        self.de_detector_info.setMinimumSize(QSize(0, 30))
        self.de_detector_info.setMaximumSize(QSize(16777215, 60))
        self.de_detector_info.setFont(font)
        self.de_detector_info.setAlignment(Qt.AlignCenter)
        self.de_detector_info.setObjectName("de_detector_info")
        self.de_layout.addWidget(self.de_detector_info)
        self.de_element_box = QComboBox(self.main_layout)
        self.de_element_box.setMinimumSize(QSize(0, 40))
        self.de_element_box.setMaximumSize(QSize(16777215, 60))
        self.de_element_box.setPalette(palette)
        self.de_element_box.setFont(font)
        self.de_element_box.setStyleSheet("background-color: rgb(85, 85, 127);\ncolor: rgb(255, 255, 255);")
        self.de_element_box.setObjectName("de_element_box")
        self.de_element_box.addItem("")
        self.de_element_box.addItem("")
        self.de_element_box.addItem("")
        self.de_layout.addWidget(self.de_element_box)
        self.de_thickness_layout = QHBoxLayout()
        self.de_thickness_layout.setObjectName("de_thickness_layout")
        self.de_thick_info = QLabel(self.main_layout)
        self.de_thick_info.setMinimumSize(QSize(130, 50))
        self.de_thick_info.setMaximumSize(QSize(260, 80))
        self.de_thick_info.setFont(font)
        self.de_thick_info.setObjectName("de_thick_info")
        self.de_thickness_layout.addWidget(self.de_thick_info)
        self.de_thickness_box = QDoubleSpinBox(self.main_layout)
        self.de_thickness_box.setMinimumSize(QSize(100, 40))
        self.de_thickness_box.setMaximumSize(QSize(200, 80))
        self.de_thickness_box.setFont(font)
        self.de_thickness_box.setStyleSheet("background-color: rgb(85, 85, 127);\ncolor: rgb(255, 255, 255);")
        self.de_thickness_box.setAlignment(Qt.AlignCenter)
        self.de_thickness_box.setMaximum(999999999.99)
        self.de_thickness_box.setProperty("value", 50.0)
        self.de_thickness_box.setPalette(palette)
        self.de_thickness_box.setObjectName("de_thickness_box")
        self.de_thickness_layout.addWidget(self.de_thickness_box)
        self.de_layout.addLayout(self.de_thickness_layout)
        self.de_resolution_layout = QHBoxLayout()
        self.de_resolution_layout.setObjectName("de_resolution_layout")
        self.de_res_info = QLabel(self.main_layout)
        self.de_res_info.setMinimumSize(QSize(130, 50))
        self.de_res_info.setMaximumSize(QSize(260, 50))
        self.de_res_info.setFont(font)
        self.de_res_info.setObjectName("de_res_info")
        self.de_resolution_layout.addWidget(self.de_res_info)
        self.de_resolution_box = QDoubleSpinBox(self.main_layout)
        self.de_resolution_box.setMinimumSize(QSize(100, 40))
        self.de_resolution_box.setMaximumSize(QSize(200, 80))
        self.de_resolution_box.setFont(font)
        self.de_resolution_box.setStyleSheet("background-color: rgb(85, 85, 127);\ncolor: rgb(255, 255, 255);")
        self.de_resolution_box.setAlignment(Qt.AlignCenter)
        self.de_resolution_box.setMaximum(999999999.99)
        self.de_resolution_box.setProperty("value", 1.0)
        self.de_resolution_box.setPalette(palette)
        self.de_resolution_box.setObjectName("de_resolution_box")
        self.de_resolution_layout.addWidget(self.de_resolution_box)
        self.de_layout.addLayout(self.de_resolution_layout)
        self.detector_layout.addLayout(self.de_layout)
        self.e_layout = QVBoxLayout()
        self.e_layout.setObjectName("e_layout")
        self.e_detector_info = QLabel(self.main_layout)
        self.e_detector_info.setMinimumSize(QSize(0, 30))
        self.e_detector_info.setMaximumSize(QSize(16777215, 60))
        self.e_detector_info.setFont(font)
        self.e_detector_info.setAlignment(Qt.AlignCenter)
        self.e_detector_info.setObjectName("e_detector_info")
        self.e_layout.addWidget(self.e_detector_info)
        self.e_element_box = QComboBox(self.main_layout)
        self.e_element_box.setMinimumSize(QSize(0, 40))
        self.e_element_box.setMaximumSize(QSize(16777215, 60))
        self.e_element_box.setPalette(palette)
        self.e_element_box.setFont(font)
        self.e_element_box.setStyleSheet("background-color: rgb(85, 85, 127);\ncolor: rgb(255, 255, 255);")
        self.e_element_box.setObjectName("e_element_box")
        self.e_element_box.addItem("")
        self.e_element_box.addItem("")
        self.e_element_box.addItem("")
        self.e_layout.addWidget(self.e_element_box)
        self.e_thickness_layout = QHBoxLayout()
        self.e_thickness_layout.setObjectName("e_thickness_layout")
        self.e_thick_info = QLabel(self.main_layout)
        self.e_thick_info.setMinimumSize(QSize(130, 50))
        self.e_thick_info.setMaximumSize(QSize(260, 80))
        self.e_thick_info.setFont(font)
        self.e_thick_info.setObjectName("e_thick_info")
        self.e_thickness_layout.addWidget(self.e_thick_info)
        self.e_thickness_box = QDoubleSpinBox(self.main_layout)
        self.e_thickness_box.setMinimumSize(QSize(100, 40))
        self.e_thickness_box.setMaximumSize(QSize(200, 80))
        self.e_thickness_box.setFont(font)
        self.e_thickness_box.setStyleSheet("background-color: rgb(85, 85, 127);\ncolor: rgb(255, 255, 255);")
        self.e_thickness_box.setAlignment(Qt.AlignCenter)
        self.e_thickness_box.setMaximum(999999999.99)
        self.e_thickness_box.setProperty("value", 2000.0)
        self.e_thickness_box.setPalette(palette)
        self.e_thickness_box.setObjectName("e_thickness_box")
        self.e_thickness_layout.addWidget(self.e_thickness_box)
        self.e_layout.addLayout(self.e_thickness_layout)
        self.e_resolution_layout = QHBoxLayout()
        self.e_resolution_layout.setObjectName("e_resolution_layout")
        self.e_res_info = QLabel(self.main_layout)
        self.e_res_info.setMinimumSize(QSize(130, 50))
        self.e_res_info.setMaximumSize(QSize(260, 50))
        self.e_res_info.setFont(font)
        self.e_res_info.setObjectName("e_res_info")
        self.e_resolution_layout.addWidget(self.e_res_info)
        self.e_resolution_box = QDoubleSpinBox(self.main_layout)
        self.e_resolution_box.setMinimumSize(QSize(100, 40))
        self.e_resolution_box.setMaximumSize(QSize(200, 80))
        self.e_resolution_box.setFont(font)
        self.e_resolution_box.setStyleSheet("background-color: rgb(85, 85, 127);\ncolor: rgb(255, 255, 255);")
        self.e_resolution_box.setAlignment(Qt.AlignCenter)
        self.e_resolution_box.setMaximum(999999999.99)
        self.e_resolution_box.setProperty("value", 1.0)
        self.e_resolution_box.setPalette(palette)
        self.e_resolution_box.setObjectName("e_resolution_box")
        self.e_resolution_layout.addWidget(self.e_resolution_box)
        self.e_layout.addLayout(self.e_resolution_layout)
        self.detector_layout.addLayout(self.e_layout)
        self.telescope_layout.addLayout(self.detector_layout)
        self.verticalLayout.addLayout(self.telescope_layout)
        self.distance_layout = QHBoxLayout()
        self.distance_layout.setObjectName("distance_layout")
        self.beam_span_label = QLabel(self.main_layout)
        self.beam_span_label.setMinimumSize(QSize(370, 40))
        self.beam_span_label.setMaximumSize(QSize(370, 80))
        self.beam_span_label.setObjectName("beam_span_label")
        self.distance_layout.addWidget(self.beam_span_label)
        self.distance_box = QDoubleSpinBox(self.main_layout)
        self.distance_box.setMinimumSize(QSize(150, 40))
        self.distance_box.setMaximumSize(QSize(16777215, 80))
        self.distance_box.setPalette(palette)
        self.distance_box.setStyleSheet("background-color: rgb(85, 85, 127);color: rgb(255, 255, 255);")
        self.distance_box.setAlignment(Qt.AlignCenter)
        self.distance_box.setMaximum(999999.0)
        self.distance_box.setSingleStep(0.1)
        self.distance_box.setObjectName("distance_box")
        self.distance_layout.addWidget(self.distance_box)
        self.verticalLayout.addLayout(self.distance_layout)
        self.radius_layout = QHBoxLayout()
        self.radius_layout.setObjectName("radius_layout")
        self.radius_label = QLabel(self.main_layout)
        self.radius_label.setMinimumSize(QSize(370, 40))
        self.radius_label.setMaximumSize(QSize(370, 80))
        self.radius_label.setObjectName("radius_label")
        self.radius_layout.addWidget(self.radius_label)
        self.radius_box = QDoubleSpinBox(self.main_layout)
        self.radius_box.setMinimumSize(QSize(150, 40))
        self.radius_box.setMaximumSize(QSize(16777215, 80))
        self.radius_box.setPalette(palette)
        self.radius_box.setStyleSheet("background-color: rgb(85, 85, 127);color: rgb(255, 255, 255);")
        self.radius_box.setAlignment(Qt.AlignCenter)
        self.radius_box.setMaximum(999999.0)
        self.radius_box.setSingleStep(0.1)
        self.radius_box.setObjectName("collimator_box")
        self.radius_layout.addWidget(self.radius_box)
        self.verticalLayout.addLayout(self.radius_layout)
        self.integrator_layout = QHBoxLayout()
        self.integrator_layout.setObjectName("integrator_layout")
        self.integrator_label = QLabel(self.main_layout)
        self.integrator_label.setMinimumSize(QSize(370, 40))
        self.integrator_label.setMaximumSize(QSize(355, 80))
        self.integrator_label.setObjectName("integrator_label")
        self.integrator_layout.addWidget(self.integrator_label)
        self.integrator_line = QLineEdit(self.main_layout)
        self.integrator_line.setMinimumSize(QSize(150, 40))
        self.integrator_line.setMaximumSize(QSize(16777215, 80))
        self.integrator_line.setStyleSheet("background-color: rgb(85, 85, 127);color: rgb(255, 255, 255);")
        self.integrator_line.setAlignment(Qt.AlignCenter)
        self.integrator_line.setObjectName("integrator_line")
        self.integrator_layout.addWidget(self.integrator_line)
        self.integrator_correct_label = QLabel(self.main_layout)
        self.integrator_correct_label.setMinimumSize(QSize(0, 40))
        self.integrator_correct_label.setMaximumSize(QSize(120, 80))
        self.integrator_correct_label.setObjectName("integrator_correct_label")
        self.integrator_layout.addWidget(self.integrator_correct_label)
        self.verticalLayout.addLayout(self.integrator_layout)
        self.congruence_layout = QHBoxLayout()
        self.congruence_layout.setObjectName("congruence_layout")
        self.congruence_label = QLabel(self.main_layout)
        self.congruence_label.setMinimumSize(QSize(370, 40))
        self.congruence_label.setMaximumSize(QSize(370, 80))
        self.congruence_label.setObjectName("congruence_label")
        self.congruence_layout.addWidget(self.congruence_label)
        self.congruence_line = QLineEdit(self.main_layout)
        self.congruence_line.setMinimumSize(QSize(150, 40))
        self.congruence_line.setMaximumSize(QSize(16777215, 80))
        self.congruence_line.setStyleSheet("background-color: rgb(85, 85, 127);color: rgb(255, 255, 255);")
        self.congruence_line.setAlignment(Qt.AlignCenter)
        self.congruence_line.setObjectName("congruence_line")
        self.congruence_layout.addWidget(self.congruence_line)
        self.congruence_correct_label = QLabel(self.main_layout)
        self.congruence_correct_label.setMinimumSize(QSize(0, 40))
        self.congruence_correct_label.setMaximumSize(QSize(120, 80))
        self.congruence_correct_label.setObjectName("congruence_correct_label")
        self.congruence_layout.addWidget(self.congruence_correct_label)
        self.verticalLayout.addLayout(self.congruence_layout)
        self.intconst_layout = QHBoxLayout()
        self.intconst_layout.setObjectName("intconst_layout")
        self.intconst_label = QLabel(self.main_layout)
        self.intconst_label.setMinimumSize(QSize(370, 40))
        self.intconst_label.setMaximumSize(QSize(370, 80))
        self.intconst_label.setObjectName("intconst_label")
        self.intconst_layout.addWidget(self.intconst_label)
        self.intconst_line = QLineEdit(self.main_layout)
        self.intconst_line.setMinimumSize(QSize(150, 40))
        self.intconst_line.setMaximumSize(QSize(16777215, 80))
        self.intconst_line.setStyleSheet("background-color: rgb(85, 85, 127);color: rgb(255, 255, 255);")
        self.intconst_line.setAlignment(Qt.AlignCenter)
        self.intconst_line.setObjectName("intconst_line")
        self.intconst_layout.addWidget(self.intconst_line)
        self.intconst_correct_label = QLabel(self.main_layout)
        self.intconst_correct_label.setMinimumSize(QSize(0, 40))
        self.intconst_correct_label.setMaximumSize(QSize(120, 80))
        self.intconst_correct_label.setObjectName("intconst_correct_label")
        self.intconst_layout.addWidget(self.intconst_correct_label)
        self.verticalLayout.addLayout(self.intconst_layout)
        self.pushButton = QPushButton(self.main_layout)
        self.pushButton.setMinimumSize(QSize(0, 70))
        self.pushButton.setMaximumSize(QSize(16777215, 120))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.horizontalLayout.addWidget(self.main_layout)
        spacerItem1 = QSpacerItem(0, 0, QSizePolicy.Preferred, QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        FileConfigWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(FileConfigWindow)
        QMetaObject.connectSlotsByName(FileConfigWindow)

    def retranslateUi(self, FileConfigWindow):
        _translate = QCoreApplication.translate
        FileConfigWindow.setWindowTitle(_translate("FileConfigWindow", "dSigma — Experiment file config editor"))
        self.beam_label.setText(_translate("FileConfigWindow", "Beam  ---------------------------------------"))
        self.beam_line.setPlaceholderText(_translate("FileConfigWindow", "Examples: d, alpha, 16O"))
        self.beam_correct_label.setText(_translate("FileConfigWindow", "Correct 👍"))
        self.target_label.setText(_translate("FileConfigWindow", "Target --------------------------------------------"))
        self.target_line.setPlaceholderText(_translate("FileConfigWindow", "Examples: Pb208, Li-7, proton"))
        self.target_correct_label.setText(_translate("FileConfigWindow", "Correct 👍"))
        self.energy_label.setText(_translate("FileConfigWindow", "Beam Energy ----------------------------------------------"))
        self.energy_box.setSuffix(_translate("FileConfigWindow", " MeV"))
        self.angle_label.setText(_translate("FileConfigWindow", "Laboratory Angle ---------------------------------"))
        self.angle_box.setSuffix(_translate("FileConfigWindow", " deg."))
        self.angle_correct_label.setText(_translate("FileConfigWindow", "Correct 👍"))
        self.telescope_info.setText(_translate("FileConfigWindow", "Telescope"))
        self.de_detector_info.setText(_translate("FileConfigWindow", "dE Detector"))
        self.de_element_box.setItemText(0, _translate("FileConfigWindow", "Si"))
        self.de_element_box.setItemText(1, _translate("FileConfigWindow", "HpGe"))
        self.de_element_box.setItemText(2, _translate("FileConfigWindow", "C3H6"))
        self.de_thick_info.setText(_translate("FileConfigWindow", "Thickness:"))
        self.de_thickness_box.setSuffix(_translate("FileConfigWindow", " mkm"))
        self.de_res_info.setText(_translate("FileConfigWindow", "Resolution:"))
        self.de_resolution_box.setSuffix(_translate("FileConfigWindow", " keV"))
        self.e_detector_info.setText(_translate("FileConfigWindow", "E Detector"))
        self.e_element_box.setItemText(0, _translate("FileConfigWindow", "Si"))
        self.e_element_box.setItemText(1, _translate("FileConfigWindow", "HpGe"))
        self.e_element_box.setItemText(2, _translate("FileConfigWindow", "C3H6"))
        self.e_thick_info.setText(_translate("FileConfigWindow", "Thickness:"))
        self.e_thickness_box.setSuffix(_translate("FileConfigWindow", " mkm"))
        self.e_res_info.setText(_translate("FileConfigWindow", "Resolution:"))
        self.e_resolution_box.setSuffix(_translate("FileConfigWindow", " keV"))
        self.beam_span_label.setText(_translate("FileConfigWindow", "Beam span base ---------------------------------"))
        self.distance_box.setSuffix(_translate("FileConfigWindow", " mm"))
        self.radius_label.setText(_translate("FileConfigWindow", "Collimator radius ---------------------------------"))
        self.radius_box.setSuffix(_translate("FileConfigWindow", " mm"))
        self.integrator_label.setText(_translate("FileConfigWindow", "Integrator counts ---------------------------------"))
        self.integrator_line.setPlaceholderText(_translate("FileConfigWindow", "Examples: 1.23e+10, 1345678"))
        self.integrator_correct_label.setText(_translate("FileConfigWindow", "Correct 👍"))
        self.congruence_label.setText(_translate("FileConfigWindow", "Congruence counts ---------------------------------"))
        self.congruence_line.setPlaceholderText(_translate("FileConfigWindow", "Examples: 1.23e+10, 1345678"))
        self.congruence_correct_label.setText(_translate("FileConfigWindow", "Correct 👍"))
        self.intconst_label.setText(_translate("FileConfigWindow", "Integrator constant ---------------------------------"))
        self.intconst_line.setPlaceholderText(_translate("FileConfigWindow", "Examples: 1.23e-10, 0.000012"))
        self.intconst_correct_label.setText(_translate("FileConfigWindow", "Correct 👍"))
        self.pushButton.setText(_translate("FileConfigWindow", "Apply Changes"))


class FileEditor(QMainWindow, Ui_FileConfigWindow):
    def __init__(self, file: str) -> None:
        # WINDOW SETUP
        super().__init__()
        self.setupUi(self)
        self.setWindowIcon(QIcon("./icon.ico"))

        # DATA
        self.file = file
        self.matrix = Matrix(Decoder(file))

        self.set_all()

    def set_all(self) -> None:
        self.beam_line.setText(str(self.matrix.experiment.beam))
        self.target_line.setText(str(self.matrix.experiment.target))
        self.energy_box.setProperty("value", self.matrix.experiment.beam_energy)
        self.angle_box.setProperty("value", self.matrix.angle)

        self.de_thickness_box.setProperty("value", self.matrix.electronics.de_detector.thickness)
        self.de_resolution_box.setProperty("value", self.matrix.electronics.de_detector.resolution * 1e3)
        self.e_thickness_box.setProperty("value", self.matrix.electronics.e_detector.thickness)
        self.e_resolution_box.setProperty("value", self.matrix.electronics.e_detector.resolution * 1e3)

        self.distance_box.setProperty("value", self.matrix.electronics.distance)
        self.radius_box.setProperty("value", self.matrix.electronics.collimator_radius)

        self.integrator_line.setText(str(self.matrix.integrator_counts))
        self.congruence_line.setText(str(self.matrix.misscalculation))
        self.intconst_line.setText(str(self.matrix.integrator_constant))


if __name__ == "__main__":
    pass
