# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pages.matrixograph import MatrixRevWindow


class Ui_Welcome(object):
    def setupUi(self, dSigma):
        dSigma.setObjectName("dSigma")
        dSigma.resize(400, 300)
        dSigma.setMinimumSize(QtCore.QSize(400, 300))
        dSigma.setMaximumSize(QtCore.QSize(400, 300))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        dSigma.setFont(font)
        dSigma.setAutoFillBackground(False)
        dSigma.setStyleSheet("background-color: rgb(0, 0, 127);\ncolor: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(dSigma)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(dSigma)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.type_label = QtWidgets.QLabel(self.frame)
        self.type_label.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.type_label.setFont(font)
        self.type_label.setAlignment(QtCore.Qt.AlignCenter)
        self.type_label.setObjectName("type_label")
        self.verticalLayout_2.addWidget(self.type_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.input = QtWidgets.QLineEdit(self.frame)
        self.input.setMinimumSize(QtCore.QSize(200, 20))
        self.input.setMaximumSize(QtCore.QSize(16777215, 30))
        self.input.setStyleSheet("background-color: rgb(85, 85, 127);")
        self.input.setObjectName("input")
        self.horizontalLayout.addWidget(self.input)
        self.file_button = QtWidgets.QPushButton(self.frame)
        self.file_button.setMinimumSize(QtCore.QSize(20, 20))
        self.file_button.setMaximumSize(QtCore.QSize(40, 30))
        self.file_button.setStyleSheet("background-color: rgb(85, 85, 127);")
        self.file_button.setObjectName("file_button")
        self.horizontalLayout.addWidget(self.file_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.enter_button = QtWidgets.QPushButton(self.frame)
        self.enter_button.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.enter_button.setFont(font)
        self.enter_button.setStyleSheet("background-color: rgb(85, 85, 127);")
        self.enter_button.setObjectName("enter_button")
        self.verticalLayout_2.addWidget(self.enter_button)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(dSigma)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.version_label = QtWidgets.QLabel(self.frame_2)
        self.version_label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.version_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.version_label.setObjectName("version_label")
        self.verticalLayout_3.addWidget(self.version_label)
        self.info_label = QtWidgets.QLabel(self.frame_2)
        self.info_label.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.info_label.setFont(font)
        self.info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.info_label.setObjectName("info_label")
        self.verticalLayout_3.addWidget(self.info_label)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(dSigma)
        QtCore.QMetaObject.connectSlotsByName(dSigma)

    def retranslateUi(self, dSigma):
        _translate = QtCore.QCoreApplication.translate
        dSigma.setWindowTitle(_translate("dSigma", "dSigma — Welcome Page"))
        self.type_label.setText(_translate("dSigma", "Please, type the path to directory of E-dE matrices"))
        self.input.setPlaceholderText(_translate("dSigma", "Example: C:\\Users\\User\\Directory\\"))
        self.file_button.setText(_translate("dSigma", "..."))
        self.enter_button.setText(_translate("dSigma", "Enter"))
        self.version_label.setText(_translate("dSigma", "dSigma v0.1.0"))
        self.info_label.setText(_translate("dSigma", "LLENR application for analyzing spectres"))


class WelcomeWindow(QtWidgets.QDialog, Ui_Welcome):
    def __init__(self) -> None:
        super().__init__()
        self.setupUi(self)

        self.path = ''

        self.file_button.clicked.connect(self.take_directory)
        self.enter_button.clicked.connect(self.start)

    def take_directory(self) -> None:
        paths = QtWidgets.QFileDialog.getExistingDirectory(self)
        self.input.setText(paths)
        self.path = paths

    def start(self) -> None:
        if self.path == '':
            return

        self.window = MatrixRevWindow(self.path)
        self.window.show()
        self.hide()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dSigma = QtWidgets.QWidget()
    ui = Ui_Welcome()
    ui.setupUi(dSigma)
    dSigma.show()
    sys.exit(app.exec_())
